[package]
name = "db_access"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gorm = { version = "0.1.4", features = ["migration_cli"] }
tokio = { version = "1.20.1", features = ["full"] }
